USE db_quitanda;

SELECT * FROM tb_produtos;

--ORDENAR NOME POR ORDEM CRESCENTE--
SELECT * FROM tb_produtos ORDER BY Nome ASC; 

--ORDENAR NOME POR ORDEM DECRESCENTE--
SELECT * FROM tb_produtos ORDER BY Nome DESC;

--ORDENAR PREÇO POR ORDEM CRESCENTE--
SELECT * FROM tb_produtos ORDER BY Preco ASC;

--ORDENAR PREÇO POR ORDEM DECRESCENTE--
SELECT * FROM tb_produtos ORDER BY Preco DESC;

--SELECIONA ID ONDE ID = 1--
SELECT * FROM tb_produtos WHERE Id = 1;

--SELECIONA ID ONDE ID != 1--
SELECT * FROM tb_produtos WHERE NOT Id = 1;



